### ISSUE TITLE
Crear clase rounded y rounded-sm

### ISSUE THREAD

**Issue by smichelle05a** [RooftopAcademy/rooftstrap#150]
```scss
.rounded {
border-radius: 6px;
}

.rounded-sm {
border-radius: 3px;
}
```
