### ISSUE TITLE
Crear clase shadow-m

### ISSUE THREAD

**Issue by smichelle05a** [RooftopAcademy/rooftstrap#151]
```scss
.shadow-m {
	box-shadow: 0 0.5rem 0.4rem rgba(0, 0, 0, 0.075);
}
```
