### ISSUE TITLE
Crear clases rounded-top y rounded-bottom

### ISSUE THREAD

**Issue by smichelle05a** [RooftopAcademy/rooftstrap#154]
```scss
.rounded-top {
border-radius: 6px 6px 0 0;
}

.rounded-sm-top {
border-radius: 3px 3px 0 0;
}

.rounded-bottom {
border-radius: 0 0 6px 6px
}

.rounded-sm-bottom {
border-radius: 0 0 3px 3px
}
```

**Comment by Alonso-Pablo** [comment]
Podria ser:

```css
.rounded-m-top {
border-radius: 6px 6px 0 0;
}

.rounded-sm-top {
border-radius: 3px 3px 0 0;
}

.rounded-m-bottom {
border-radius: 0 0 6px 6px
}

.rounded-sm-bottom {
border-radius: 0 0 3px 3px
}
```
sm = small
m = medium
mb = medium-big (?
b = big
sb = super-big (?
