### ISSUE TITLE
Fix agregar clases pasadas por alto al reestructurar

### ISSUE THREAD

**Issue by smichelle05a** [RooftopAcademy/rooftstrap#170]
Las siguientes clases fueron pasadas por alto al momento de reestructurar:

```scss

button:disabled,
button[disabled]{
  border: 1px solid #999999;
  background-color: -var(--light-grey);
  color: var(--grey);
}

.fw-wrap {
    flex-wrap: wrap;
}

.fd-col {
    flex-direction: column;
}

.txt-overflow {
    overflow: hidden;
    text-overflow: ellipsis;
}

.shadow-sm {
  box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075) !important;
}

.shadow-hover:hover {
  box-shadow: 0 7px 16px 0 rgb(0 0 0 / 20%), 0 1px 3px 0 rgb(0 0 0 / 10%);
}

.overflow-scrollx {
  overflow-x: scroll;
}

.title {
  font: 600;
  font-size: 1.25rem;
}

.vh-100 {
  min-height: 100vh;
}

.txt-strike{
    text-decoration: line-through;
}
```
